# Generated by Django 5.2.8 on 2025-11-27 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seed', models.FloatField(default=0.5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('time_speed', models.FloatField(default=10.0)),
            ],
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField()),
                ('z', models.IntegerField()),
                ('modifications', models.JSONField(default=dict)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='game.world')),
            ],
            options={
                'unique_together': {('world', 'x', 'z')},
            },
        ),
    ]
