# Generated by Django 5.2.8 on 2025-11-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='world',
            name='time_speed',
            field=models.FloatField(default=20.0),
        ),
    ]
