# Generated by Django 5.2.8 on 2025-11-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_alter_world_time_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=80)),
                ('z', models.FloatField(default=0)),
                ('rx', models.FloatField(default=0)),
                ('ry', models.FloatField(default=0)),
                ('rz', models.FloatField(default=0)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
