# Generated by Django 5.2.8 on 2025-11-27 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='rx',
            new_name='rotation_x',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='ry',
            new_name='rotation_y',
        ),
        migrations.RemoveField(
            model_name='player',
            name='rz',
        ),
        migrations.RemoveField(
            model_name='world',
            name='time_speed',
        ),
        migrations.AddField(
            model_name='world',
            name='name',
            field=models.CharField(default='World 1', max_length=100),
        ),
        migrations.AlterField(
            model_name='world',
            name='seed',
            field=models.IntegerField(default=12345),
        ),
    ]
