# Generated by Django 5.2.8 on 2025-11-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_rename_rx_player_rotation_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='time',
            field=models.IntegerField(default=6000),
        ),
    ]
