# Generated by Django 5.2.8 on 2025-11-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_world_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='inventory',
            field=models.JSONField(default=list),
        ),
    ]
