# Generated by Django 5.2.8 on 2025-11-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_player_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='world',
            name='motd',
            field=models.CharField(default='Welcome to the Voxel World!', max_length=255),
        ),
    ]
