# Generated by Django 5.2.8 on 2025-11-30 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_world_motd'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='gamemode',
            field=models.CharField(default='survival', max_length=20),
        ),
        migrations.AddField(
            model_name='player',
            name='health',
            field=models.IntegerField(default=20),
        ),
    ]
